Lesson 4: Add news routes, controller and views
RomaOkorosso/fefu_backend_2_3 pull request #4
Opened 2021-11-09 16:31 UTC by RomaOkorosso

Извиняюсь за жирный  `<style>` в `app.blade.php`

2021-11-11 15:22 UTC, chrn-feip requested changes

2021-11-11 15:22 UTC, chrn-feip commented on app/Http/Controllers/NewsController.php
> +        $items = DB::table('news')
Мы используем ORM через модели и билдеры запросов к ним.

2021-11-11 15:22 UTC, chrn-feip commented on app/Http/Controllers/NewsController.php
> +            ->orderBy("id")
Здесь так же по убыванию сортировка. Кроме того, есть метод orderByDesc

2021-11-11 15:22 UTC, chrn-feip commented on app/Http/Controllers/NewsController.php
> +        $item = get_object_vars($item);
То же самое про ORM

2021-11-11 15:22 UTC, chrn-feip commented on routes/web.php
> +    Route::get("/", "App\Http\Controllers\NewsController@getList")->name('news_list');
Используйте use и форму записи для контроллера из документации: массив из имени класса контроллера и название метода. Так вы сможете легко попадать в контроллер из этого файла просто по клику.

2021-11-13 02:17 UTC, chrn-feip requested changes

2021-11-13 02:17 UTC, chrn-feip commented on app/Http/Controllers/NewsController.php
> +        Log::info($items);
Уберите отладочный вывод

2021-11-13 02:17 UTC, chrn-feip commented on app/Http/Controllers/NewsController.php
> +        return view("news.list", compact("items"));
Зачем вам тут compact? Вы должны работать с объектом пагинатора в шаблоне.

2021-11-13 02:17 UTC, chrn-feip commented on app/Http/Controllers/NewsController.php
> +        return view("news.detail", compact("item"));
То же самое

2021-11-13 02:17 UTC, chrn-feip commented on app/Http/Controllers/NewsController.php
> +        Log::info($item);
То же самое

2021-11-26 14:26 UTC, chrn-feip commented
Вы живы?

2021-12-12 22:30 UTC, RomaOkorosso commented
Иначе не работает, логгирование вычистил, компакт работает как и задумано, пагинация тоже

2021-12-13 00:50 UTC, chrn-feip commented
Добавьте в контрибьюторы проекта  @kivaloff

2021-12-13 00:56 UTC, merged